#!/bin/bash
git for-each-ref --format="%(refname:short)" refs/heads | while read localbranch
do
    eval $(git rev-list --left-right ${localbranch}...origin/master 2> /dev/null | awk '/^</ {ahead++} /^>/ {behind++} END {print "AHEAD="ahead " BEHIND="behind}')
    printf "%s (%s ahead | %s behind) origin/master\n" $localbranch ${AHEAD:-0} ${BEHIND:-0} 
done

