#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  if ! command -v brew &> /dev/null; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi
fi

if [ "$system_type" != "Darwin" ]; then
  NEED_SUDO=sudo
fi

if ! command -v aws &> /dev/null; then
  $NEED_SUDO pip3 install awscli
fi

if ! command -v powerline-config &> /dev/null; then
  $NEED_SUDO pip3 install powerline-status powerline-gitstatus
fi
